sudo: false
language: cpp

env:
  global:
    - BOOST_INSTALL_DIR="$HOME/.local"
    - BOOST_VERSION="1.67.0"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - pkg-config
            - libjsoncpp-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CMAKE_URL="http://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz"
        - CMAKE_COMMAND="$HOME/.local/bin/cmake"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install jsoncpp && brew upgrade cmake"
        - CMAKE_URL="http://cmake.org/files/v3.11/cmake-3.11.0-Darwin-x86_64.tar.gz"
        - CMAKE_COMMAND="cmake"

cache:
  directories:
    - $HOME/.local

before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir -p $HOME/.local
    - |
      if [ "$TRAVIS_OS_NAME" = "linux"  ]; then
        if [ ! -e $HOME/.local/bin/cmake ]; then
          echo "CMake not found in the cache, get and extract it..."
          travis_retry curl -L ${CMAKE_URL} \
            | tar -xz -C $HOME/.local --strip-components=1
        else
          echo "Using cached CMake"
        fi
      fi
compiler:
  - gcc

before_script:
  - cd $TRAVIS_BUILD_DIR
  - travis_wait source $TRAVIS_BUILD_DIR/toolchain/install-boost.sh
  - mkdir build
  - cd build
  - source $TRAVIS_BUILD_DIR/toolchain/install-boost.sh && ${CMAKE_COMMAND} -DBOOST_ROOT:PATHNAME=$BOOST_ROOT ..

script:
  - ${CXX} --version
  - echo CXXFLAGS=${CXXFLAGS}
  - make

